Repository founders-programme-2/howl, pull requests merged in 2019-05, with the labels that each got.

#65 File structure: initial file structure has been setup.
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/manifest.json
  client/src/App.js
  client/src/index.js
  client/src/serviceWorker.js
  src/airtables/index.js
  src/airtables/story.js
  src/app.js
  src/controllers/index.js
  src/router.js
  src/server.js
  src/validation/index.js
  src/validation/story.js
  src/validation/validations.js 
Labels: approved, technical

#67 Setup/express: set up a basic express server, with a route, and apply eslint airbnb style.
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  src/app.js
  src/router.js
  src/server.js
Labels: approved, technical

#68 Feature/client side linting
  .gitignore
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
Labels: awaiting-review

#69 add scripts to run in Heroku.
  package.json
Labels: approved, technical

#70 Deploy/heroku
  client/package.json
  package.json
Labels: awaiting-review, technical

#72 Fix/minor syntax errors
  client/src/App.js
Labels: awaiting-review

#77 Update gitignore
  .gitignore
Labels: approved

#83 Add travis file #56
  .travis.yml
Labels: approved

#76 Setup/react routes: setup dummy components with unique routes.
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/About/About.style.js
  client/src/Components/About/index.js
  client/src/Components/AddStory/AddStory.style.js
  client/src/Components/AddStory/index.js
  client/src/Components/Archive/Archive.style.js
  client/src/Components/Archive/index.js
  client/src/Components/Footer/Footer.style.js
  client/src/Components/Footer/index.js
  client/src/Components/Header/Header.style.js
  client/src/Components/Header/index.js
  client/src/Components/Help/Help.style.js
  client/src/Components/Help/index.js
  client/src/Components/Main/Main.style.js
  client/src/Components/Main/index.js
  client/src/Components/Resources/Resources.style.js
  client/src/Components/Resources/index.js
  client/src/Components/Results/Results.style.js
  client/src/Components/Results/index.js
  client/src/Components/Story/Story.style.js
  client/src/Components/Story/index.js
  client/src/Components/Timeline/Timeline.style.js
  client/src/Components/Timeline/index.js
  client/src/Components/Wlm/Wlm.style.js
  client/src/Components/Wlm/index.js
  client/src/Components/index.js
Labels: changes requested, technical

#88 Add environment file example
  config.env.example
Labels: approved, chore

#85 A11y setup
  client/package-lock.json
  client/package.json
  client/src/index.js
Labels: approved

#92 Feature/refactor routes to use constant urls
  client/src/App.js
  client/src/constants/navigationUrls.js
Labels: approved

#91 update read me with modules used for image upload
  README.md
Labels: approved

#94 fix import of constant urls into app
  client/src/App.js
Labels: approved

#86 Feature/photo upload: upload images to a hosting service and get a link back.
  package-lock.json
  package.json
  src/app.js
  src/middlewares/uploadImg.js
  src/router.js
Labels: changes requested, technical

#105 Feature/add route for guidelines
  client/src/App.js
  client/src/Components/Add/Add.style.js
  client/src/Components/Add/index.js
  client/src/Components/AddStory/index.js
  client/src/Components/Error404/Error404.style.js
  client/src/Components/Error404/index.js
  client/src/Components/Form/Form.style.js
  client/src/Components/Form/index.js
  client/src/Components/Landing/Landing.style.js
  client/src/Components/Landing/index.js
  client/src/Components/Main/index.js
  client/src/Components/index.js
  client/src/constants/navigationUrls.js
Labels: approved

#103 Feature/create route that handle request data and add new airtable-posts row
  README.md
  config.env.example
  package-lock.json
  package.json
  src/airtables/index.js
  src/airtables/story.js
  src/controllers/index.js
  src/controllers/story.js
  src/router.js
Labels: approved, technical

#93 Feature/global styles
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/globalStyle.js
Labels: approved

#84 Codecov setup
  .travis.yml
  client/package.json
  codecov.yml
  package-lock.json
  package.json
  tests/index.test.js
Labels: approved

#106 Feature/header navigation component
  client/package-lock.json
  client/src/App.js
  client/src/Assets/logo.svg
  client/src/Components/About/index.js
  client/src/Components/Archive/index.js
  client/src/Components/Common/Footer/Footer.style.js
  client/src/Components/Common/Footer/index.js
  client/src/Components/Common/Header/Header.style.js
  client/src/Components/Common/Header/index.js
  client/src/Components/Header/Header.style.js
  client/src/Components/Header/index.js
  client/src/Components/Landing/index.js
  client/src/Components/Main/index.js
  client/src/Components/Resources/index.js
  client/src/Components/Story/index.js
  client/src/Components/Timeline/index.js
  client/src/Components/Wlm/index.js
  client/src/Components/index.js
  client/src/globalStyle.js
  package-lock.json
Labels: approved

#107 Feature/update pages
  client/public/index.html
  client/public/reset.css
  client/src/Components/About/index.js
  client/src/Components/Add/index.js
  client/src/Components/Common/Header/Header.style.js
  client/src/Components/Common/Header/index.js
  client/src/Components/Landing/Landing.style.js
  client/src/Components/Landing/index.js
  client/src/Components/Resources/index.js
  client/src/Components/Resources/resourcesData.js
  client/src/Components/Wlm/index.js
  client/src/assets/landing_page.jpg
  client/src/globalStyle.js
Labels: awaiting-review, changes requested

#115 Feature/form contact info: contact info and details
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/Components/Common/Header/index.js
  client/src/Components/Form/ContactInfo/ContactInfo.style.js
  client/src/Components/Form/ContactInfo/index.js
  client/src/Components/Form/ContactInfo/muiStyles.js
  client/src/Components/Form/Details/DatePicker/index.js
  client/src/Components/Form/Details/DatePicker/muiStyles.js
  client/src/Components/Form/Details/Details.style.js
  client/src/Components/Form/Details/index.js
  client/src/Components/Form/Details/muiStyles.js
  client/src/Components/Form/index.js
  client/src/Components/Landing/Landing.style.js
  client/src/Components/Landing/index.js
  client/src/Components/muIndex.js
  client/src/assets/logo.svg
Labels: approved

#123 Feature/form post: 3rd component of form.
  client/src/Components/Form/Post/Post.style.js
  client/src/Components/Form/Post/attach.png
  client/src/Components/Form/Post/index.js
  client/src/Components/Form/Post/muiStyles.js
  client/src/Components/Form/index.js
Labels: approved

#120 Chore/Update development mode scripts
  client/package.json
  package.json
Labels: approved

#125 update readme
  README.md
Labels: awaiting-review

#128 style about page
  client/src/Components/About/About.style.js
  client/src/Components/About/index.js
  client/src/Components/Landing/index.js
  client/src/globalStyle.js
Labels: approved

#132 Fix/routing of header
  client/src/Components/Add/Add.style.js
  client/src/Components/Add/index.js
  client/src/Components/Common/Header/index.js
Labels: approved

#131 Feature/form additional: 4th part and last of the form :)
  client/src/Components/About/About.style.js
  client/src/Components/About/index.js
  client/src/Components/Form/AdditionalInfo/index.js
  client/src/Components/Form/AdditionalInfo/muiStyles.js
  client/src/Components/Form/data.json
  client/src/Components/Form/index.js
  client/src/Components/Landing/index.js
  client/src/Components/muIndex.js
Labels: approved

#134 Feature/info pg styling
  client/src/Components/About/About.style.js
  client/src/Components/About/index.js
  client/src/Components/Landing/Landing.style.js
  client/src/Components/Landing/index.js
  client/src/Components/Wlm/Wlm.style.js
  client/src/Components/Wlm/index.js
  client/src/globalStyle.js
Labels: approved

#136 Fix/all eslint: fix all eslint errors/warnings on front and back.
  client/src/Components/Add/Add.style.js
  client/src/Components/Add/index.js
  client/src/serviceWorker.js
  src/middlewares/uploadImg.js
Labels: approved

#140 Fix/addcheckbox: Add missing checkbox and pass it a state and a handler.
  client/src/Components/Form/Post/Post.style.js
  client/src/Components/Form/Post/index.js
  client/src/Components/Form/index.js
Labels: approved, technical

#142 refactor style to mostly live in global
  client/src/Components/About/About.style.js
  client/src/Components/About/index.js
  client/src/Components/Landing/Landing.style.js
  client/src/Components/Landing/index.js
  client/src/Components/Resources/Resources.style.js
  client/src/Components/Resources/index.js
  client/src/Components/Resources/resourcesData.js
  client/src/Components/Wlm/Wlm.style.js
  client/src/Components/Wlm/index.js
  client/src/globalStyle.js
Labels: awaiting-review

#146 fix eslint issues on client folder.
  client/src/Components/About/About.style.js
  client/src/Components/About/index.js
  client/src/Components/Landing/Landing.style.js
  client/src/Components/Landing/index.js
  client/src/Components/Resources/Resources.style.js
  client/src/Components/Resources/index.js
  client/src/Components/Wlm/Wlm.style.js
  client/src/Components/Wlm/index.js
Labels: approved, technical

#143 Feature/update archive page
  client/src/Components/About/About.style.js
  client/src/Components/About/index.js
  client/src/Components/Archive/index.js
  client/src/Components/Resources/Resources.style.js
  client/src/Components/Timeline/index.js
  client/src/globalStyle.js
Labels: approved

#144 Feature: add input handlers and state.
  client/src/Components/Form/AdditionalInfo/index.js
  client/src/Components/Form/ContactInfo/index.js
  client/src/Components/Form/Details/DatePicker/index.js
  client/src/Components/Form/Details/index.js
  client/src/Components/Form/Post/index.js
  client/src/Components/Form/index.js
Labels: approved

#150 Feature/add file upload handler: setup fileUpload handler and state and pass them as props to Post component.
  client/package-lock.json
  client/package.json
  client/src/Components/Form/Post/index.js
  client/src/Components/Form/index.js
  src/middlewares/uploadImg.js
  src/router.js
Labels: approved, technical

#133 Feature/footer search component
  client/src/Components/Archive/index.js
  client/src/Components/Common/Footer/Footer.style.js
  client/src/Components/Common/Footer/index.js
  client/src/Components/Common/Footer/mui.style.js
  client/src/Components/Form/AdditionalInfo/index.js
  client/src/Components/Landing/index.js
  client/src/Components/Results/index.js
  client/src/Components/Story/index.js
  client/src/Components/Timeline/index.js
  client/src/Components/data.json
  client/src/Components/muIndex.js
  client/src/globalStyle.js
  package-lock.json
Labels: approved

#165 Chore/add start dev script
  package-lock.json
  package.json
Labels: approved

#145 Feature/help page
  client/src/Components/Help/Help.style.js
  client/src/Components/Help/index.js
  client/src/assets/helpDropdowns.svg
  client/src/assets/helpSearchBtn.svg
  client/src/assets/helpSearchInput.svg
  client/src/assets/helpTimeline.svg
  client/src/globalStyle.js
Labels: approved

#152 Minor fixes to Guidelines style
  client/src/Components/Add/Add.style.js
  client/src/Components/Add/index.js
Labels: approved

#158 Feature/send to BE: send form Data to be stored in Airtable :)
  client/src/Components/Form/Buttons/Buttons.style.js
  client/src/Components/Form/Buttons/index.js
  client/src/Components/Form/index.js
  client/src/Components/data.json
  src/controllers/story.js
Labels: approved, awaiting-review, conflicts-solved

#161 Fix/refactor post component
  client/src/Components/Form/Post/index.js
Labels: approved, awaiting-review, conflicts-solved

#163 Feature/form styling
  client/public/index.html
  client/src/Components/About/About.style.js
  client/src/Components/About/index.js
  client/src/Components/Add/Add.style.js
  client/src/Components/Add/index.js
  client/src/Components/Form/AdditionalInfo/index.js
  client/src/Components/Form/AdditionalInfo/muiStyles.js
  client/src/Components/Form/Buttons/Buttons.style.js
  client/src/Components/Form/Buttons/index.js
  client/src/Components/Form/ContactInfo/ContactInfo.style.js
  client/src/Components/Form/ContactInfo/index.js
  client/src/Components/Form/ContactInfo/muiStyles.js
  client/src/Components/Form/Details/DatePicker/index.js
  client/src/Components/Form/Details/DatePicker/muiStyles.js
  client/src/Components/Form/Details/index.js
  client/src/Components/Form/Details/muiStyles.js
  client/src/Components/Form/Form.style.js
  client/src/Components/Form/Post/index.js
  client/src/Components/Form/Post/muiStyles.js
  client/src/Components/Form/index.js
  src/controllers/story.js
Labels: approved, conflicts-solved

#164 Chore/backend testing
  package-lock.json
  package.json
  src/airtables/story.js
  src/app.js
  tests/assets/textFile.txt
  tests/assets/wood.jpg
  tests/router.test.js
Labels: approved

#180 Feature/footer functionality frontend
  client/src/Components/Common/Footer/index.js
Labels: approved

#184 Feature/route story: each time a story is requested send the data back issue #79
  src/controllers/getStory.js
  src/controllers/index.js
  src/router.js
Labels: approved, technical

#186 Feature/archive show stories
  client/src/Components/Archive/Entry/Entry.style.js
  client/src/Components/Archive/Entry/index.js
  client/src/Components/Archive/index.js
  src/controllers/feed.js
  src/controllers/index.js
  src/router.js
Labels: approved

#191 Feature/display story FE: Recieve data on frontend and display it./ Refactor backend code.
  client/src/Components/Story/Story.style.js
  client/src/Components/Story/index.js
  client/src/globalStyle.js
  src/controllers/getStory.js
Labels: approved

#182 Fix/responsive pages
  client/package-lock.json
  client/src/Components/Common/Footer/Footer.style.js
  client/src/Components/Common/Footer/mui.style.js
  client/src/Components/Common/Header/Header.style.js
  client/src/Components/Common/Header/index.js
  client/src/Components/Form/AdditionalInfo/muiStyles.js
  client/src/Components/Form/ContactInfo/muiStyles.js
  client/src/Components/Form/Details/DatePicker/muiStyles.js
  client/src/Components/Form/Details/muiStyles.js
  client/src/Components/Form/Form.style.js
  client/src/Components/Form/Post/Post.style.js
  client/src/Components/Form/Post/index.js
  client/src/Components/Form/Post/muiStyles.js
  client/src/Components/Form/index.js
  client/src/Components/Landing/Landing.style.js
  client/src/constants/responsiveSizes.js
  client/src/globalStyle.js
  package-lock.json
Labels: approved

#195 Feature/display story by url: retrieve data based on id in URL. Display story's status: approved, pending, not_found.
  client/src/Components/Story/Story.style.js
  client/src/Components/Story/index.js
  client/src/constants/navigationUrls.js
  src/controllers/getStory.js
Labels: approved

#190 Chore/frontend testing
  client/package-lock.json
  client/package.json
  client/src/App.test.js
  client/src/Components/About/__snapshots__/index.test.js.snap
  client/src/Components/About/index.test.js
  client/src/Components/Add/__snapshots__/index.test.js.snap
  client/src/Components/Add/index.test.js
  client/src/Components/Archive/__snapshots__/index.test.js.snap
  client/src/Components/Archive/index.test.js
  client/src/Components/Common/Footer/__snapshots__/index.test.js.snap
  client/src/Components/Common/Footer/index.test.js
  client/src/Components/Common/Header/__snapshots__/index.test.js.snap
  client/src/Components/Common/Header/index.test.js
  client/src/Components/Error404/__snapshots__/index.test.js.snap
  client/src/Components/Error404/index.test.js
  client/src/Components/Form/AdditionalInfo/__snapshots__/index.test.js.snap
  client/src/Components/Form/AdditionalInfo/index.test.js
  client/src/Components/Form/Buttons/__snapshots__/index.test.js.snap
  client/src/Components/Form/Buttons/index.test.js
  client/src/Components/Form/ContactInfo/__snapshots__/index.test.js.snap
  client/src/Components/Form/ContactInfo/index.test.js
  client/src/Components/Form/Details/DatePicker/__snapshots__/index.test.js.snap
  client/src/Components/Form/Details/DatePicker/index.test.js
  client/src/Components/Form/Details/__snapshots__/index.test.js.snap
  client/src/Components/Form/Details/index.test.js
  client/src/Components/Form/Post/Loader/__snapshots__/index.test.js.snap
  client/src/Components/Form/Post/Loader/index.test.js
  client/src/Components/Form/Post/__snapshots__/index.test.js.snap
  client/src/Components/Form/Post/index.test.js
  client/src/Components/Form/__snapshots__/index.test.js.snap
  client/src/Components/Form/index.test.js
  client/src/Components/Help/__snapshots__/index.test.js.snap
  client/src/Components/Help/index.test.js
  client/src/Components/Landing/__snapshots__/index.test.js.snap
  client/src/Components/Landing/index.test.js
  client/src/Components/Main/__snapshots__/index.test.js.snap
  client/src/Components/Main/index.test.js
  client/src/Components/Resources/__snapshots__/index.test.js.snap
  client/src/Components/Resources/index.test.js
  client/src/Components/Results/__snapshots__/index.test.js.snap
  client/src/Components/Results/index.test.js
  client/src/Components/Story/__snapshots__/index.test.js.snap
  client/src/Components/Story/index.test.js
  client/src/Components/Timeline/__snapshots__/index.test.js.snap
  client/src/Components/Timeline/index.test.js
  client/src/Components/Wlm/__snapshots__/index.test.js.snap
  client/src/Components/Wlm/index.test.js
  client/src/__snapshots__/App.test.js.snap
  package.json
Labels: approved

#200 Feature/form validation: display error/status messages for the user.
  client/package-lock.json
  client/package.json
  client/src/Components/Form/AdditionalInfo/AdditionalInfo.style.js
  client/src/Components/Form/AdditionalInfo/index.js
  client/src/Components/Form/ContactInfo/ContactInfo.style.js
  client/src/Components/Form/ContactInfo/index.js
  client/src/Components/Form/Details/Details.style.js
  client/src/Components/Form/Details/index.js
  client/src/Components/Form/Form.style.js
  client/src/Components/Form/Post/Post.style.js
  client/src/Components/Form/Post/index.js
  client/src/Components/Form/index.js
  client/src/Components/Form/validation.js
  client/src/Components/Landing/Landing.style.js
Labels: Discuss, approved, conflicts-solved

#206 Feature/add spinners: display react spinners in `/story/:id` and `/archive/feed` til data is loaded.
  client/src/Components/Archive/Archive.style.js
  client/src/Components/Archive/index.js
  client/src/Components/BounceLoader/index.js
  client/src/Components/Story/Story.style.js
  client/src/Components/Story/index.js
Labels: approved

#207 Fix/desktop landing layout
  client/src/Components/Landing/Landing.style.js
  client/src/constants/responsiveSizes.js
Labels: approved

#203 Chore/header title color
  client/src/Components/Common/Header/Header.style.js
  client/src/Components/Common/Header/index.js
Labels: awaiting-review

#199 Handle missing data in feed
  client/src/Components/Archive/Entry/index.js
Labels: approved, conflicts-solved

#215 Fix/footer tags dropdown style: fix style and make it responsive.
  client/src/Components/Common/Footer/Footer.style.js
  client/src/Components/Common/Footer/index.js
  client/src/Components/Common/Footer/mui.style.js
Labels: approved, styling

#213 Chore/update testing snapshots
  client/package-lock.json
  client/package.json
  client/src/Components/Archive/__snapshots__/index.test.js.snap
  client/src/Components/Common/Header/__snapshots__/index.test.js.snap
  client/src/Components/Form/AdditionalInfo/__snapshots__/index.test.js.snap
  client/src/Components/Form/ContactInfo/__snapshots__/index.test.js.snap
  client/src/Components/Form/Details/__snapshots__/index.test.js.snap
  client/src/Components/Form/Post/__snapshots__/index.test.js.snap
  client/src/Components/Form/__snapshots__/index.test.js.snap
  client/src/Components/Help/__snapshots__/index.test.js.snap
  client/src/Components/Landing/__snapshots__/index.test.js.snap
  client/src/Components/Results/__snapshots__/index.test.js.snap
  client/src/Components/Story/__snapshots__/index.test.js.snap
  client/src/Components/Story/index.test.js
  client/src/Components/Timeline/__snapshots__/index.test.js.snap
  client/src/__snapshots__/App.test.js.snap
Labels: Refactor, approved, chore

#237 Fix/update landing page
  client/package-lock.json
  client/src/assets/landing_page.jpg
Labels: approved

#235 add scotland and order tags and categories #224 #234
  client/src/Components/data.json
Labels: Refactor, approved

#233 replace name with name or psedu-name #224
  client/src/Components/Form/ContactInfo/__snapshots__/index.test.js.snap
  client/src/Components/Form/ContactInfo/index.js
  client/src/Components/Form/__snapshots__/index.test.js.snap
Labels: Refactor, approved

#244 Fix/small change header order
  client/package-lock.json
  client/package.json
  client/src/Components/Archive/Entry/index.js
  client/src/Components/Archive/__snapshots__/index.test.js.snap
  client/src/Components/Common/Footer/Footer.style.js
  client/src/Components/Common/Footer/index.js
  client/src/Components/Common/Footer/mui.style.js
  client/src/Components/Common/Header/Header.style.js
  client/src/Components/Common/Header/__snapshots__/index.test.js.snap
  client/src/Components/Common/Header/index.js
  client/src/Components/Form/AdditionalInfo/__snapshots__/index.test.js.snap
  client/src/Components/Form/ContactInfo/__snapshots__/index.test.js.snap
  client/src/Components/Form/Details/__snapshots__/index.test.js.snap
  client/src/Components/Form/Post/__snapshots__/index.test.js.snap
  client/src/Components/Form/__snapshots__/index.test.js.snap
  client/src/Components/Help/__snapshots__/index.test.js.snap
  client/src/Components/Landing/__snapshots__/index.test.js.snap
  client/src/Components/Results/__snapshots__/index.test.js.snap
  client/src/Components/Story/__snapshots__/index.test.js.snap
  client/src/Components/Story/index.test.js
  client/src/Components/Timeline/__snapshots__/index.test.js.snap
  client/src/__snapshots__/App.test.js.snap
  client/src/assets/landing_page.jpg
Labels: Refactor

#239 replace landing page with original img& included new image on howl pg
  client/package.json
  client/src/Components/About/About.style.js
  client/src/Components/About/__snapshots__/index.test.js.snap
  client/src/Components/About/index.js
  client/src/__snapshots__/App.test.js.snap
  client/src/assets/about_page.jpg
  client/src/assets/landing_page.jpg
Labels: approved

#236 Fix/add footer to all pages
  client/package-lock.json
  client/src/Components/About/__snapshots__/index.test.js.snap
  client/src/Components/About/index.js
  client/src/Components/About/index.test.js
  client/src/Components/Add/index.test.js
  client/src/Components/Archive/index.test.js
  client/src/Components/Common/Header/index.js
  client/src/Components/Common/Header/index.test.js
  client/src/Components/Error404/index.test.js
  client/src/Components/Form/ContactInfo/index.test.js
  client/src/Components/Form/Details/index.js
  client/src/Components/Form/Details/index.test.js
  client/src/Components/Form/Post/index.test.js
  client/src/Components/Form/index.test.js
  client/src/Components/Help/index.test.js
  client/src/Components/Landing/index.test.js
  client/src/Components/Main/index.test.js
  client/src/Components/Resources/Resources.style.js
  client/src/Components/Resources/__snapshots__/index.test.js.snap
  client/src/Components/Resources/bibliographyData.json
  client/src/Components/Resources/index.js
  client/src/Components/Resources/index.test.js
  client/src/Components/Results/index.test.js
  client/src/Components/Story/index.js
  client/src/Components/Story/index.test.js
  client/src/Components/Timeline/index.js
  client/src/Components/Timeline/index.test.js
  client/src/Components/Wlm/__snapshots__/index.test.js.snap
  client/src/Components/Wlm/index.js
  client/src/Components/Wlm/index.test.js
Labels: approved

#240 Fix/remove datepicker and replace with dropdowns for year and month.
  client/package-lock.json
  client/package.json
  client/src/Components/Form/Details/DatePicker/__snapshots__/index.test.js.snap
  client/src/Components/Form/Details/DatePicker/index.js
  client/src/Components/Form/Details/DatePicker/index.test.js
  client/src/Components/Form/Details/DatePicker/muiStyles.js
  client/src/Components/Form/Details/index.js
  client/src/Components/Form/Details/muiStyles.js
  client/src/Components/Form/index.js
  client/src/Components/Form/validation.js
  client/src/Components/data.json
Labels: approved, conflicts-solved

#243 Fix/reg ex form validation: change forbidden characters to only { } < >
  client/src/Components/Form/validation.js
Labels: approved, conflicts-solved

#231 Fix/header links order
  client/src/Components/Common/Header/Header.style.js
  client/src/Components/Common/Header/__snapshots__/index.test.js.snap
  client/src/Components/Common/Header/index.js
  client/src/Components/Form/Details/__snapshots__/index.test.js.snap
  client/src/Components/Form/__snapshots__/index.test.js.snap
  client/src/__snapshots__/App.test.js.snap
Labels: approved, conflicts-solved

#232 Fix/make archive feed responsive. References issue #216
  client/src/Components/Archive/Entry/Entry.style.js
  client/src/Components/Archive/Entry/index.js
Labels: awaiting-review

#249 Feature/create jump to top button
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/Archive/Archive.style.js
  client/src/Components/Archive/__snapshots__/index.test.js.snap
  client/src/Components/Archive/index.js
  client/src/__snapshots__/App.test.js.snap
Labels: approved

#251 Feature/make timeline page: attach photos of timeline and add descriptions.
  client/src/Components/Timeline/Timeline.style.js
  client/src/Components/Timeline/index.js
  client/src/assets/CategorySelected.svg
  client/src/assets/SearchFunctionality.svg
  client/src/assets/SelectTimeFrame.svg
  client/src/assets/SelectedMultipleFilters.svg
  client/src/assets/StoriesHover.svg
  client/src/assets/TagsSelected.svg
  client/src/assets/TimelinePic.svg
Labels: approved
